name: Continuous Integration and Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      [main, test]
  pull_request:
    types:
      [opened, synchronize, reopened]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn install -B verify jacoco:report org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Joao-Lucas-de-Oliveira-Lima_github-actions-azure-pipeline

      - name: Set JAR file name
        run: |
          echo "JAVA_BUILD=$(ls target | grep '\.jar$')" >> $GITHUB_ENV

      #
      #dfdfdsf

      - name: Deploy to Azure Web apps
        uses: azure/webapps-deploy@v3
        env:
          AZURE_WEBAPP_PACKAGE_PATH: './target'
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.JAVA_BUILD }}'